"""WireGuard ``wg0.conf`` + ``clients.json`` generator.

No server-side WG template exists in the repo (only the client-conf generator in
``dashboard/src/lib/xray-config.ts``), so this is authored fresh against
wg-quick conventions.

The server listens on 51820/udp with ``10.7.0.1/24`` as the tunnel network.
Per-client ``[Peer]`` blocks and ``clients.json`` entries are added later by the
dashboard; the installer ships an empty peer list and a NAT config that assumes
the detected WAN interface.
"""

from __future__ import annotations

import json

from .common import Params

_SERVER_TUNNEL_IP = "10.7.0.1"
_TUNNEL_CIDR = "10.7.0.1/24"
_DNS = "1.1.1.1, 8.8.8.8"


def build_wg0_conf(p: Params) -> str:
    """Return ``/etc/wireguard/wg0.conf`` content for the server interface."""
    iface = p.wan_iface or "eth0"
    lines: list[str] = []
    lines.append("# WireGuard server config — generated by install.sh")
    lines.append("# wg-quick@wg0 manages this. Peers added by the dashboard.")
    lines.append("[Interface]")
    lines.append(f"PrivateKey = {p.wg_private}")
    lines.append(f"Address = {_TUNNEL_CIDR}")
    lines.append("ListenPort = 51820")
    lines.append("")
    lines.append("# NAT — route client traffic out the WAN interface.")
    lines.append(f"PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o {iface} -j MASQUERADE; ip6tables -A FORWARD -i %i -j ACCEPT; ip6tables -t nat -A POSTROUTING -o {iface} -j MASQUERADE")
    lines.append(f"PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o {iface} -j MASQUERADE; ip6tables -D FORWARD -i %i -j ACCEPT; ip6tables -t nat -D POSTROUTING -o {iface} -j MASQUERADE")
    lines.append("")
    lines.append("# Peer blocks appended here by the dashboard as clients are added.")
    lines.append("")
    return "\n".join(lines)


def build_clients_json() -> str:
    """Empty clients.json index. Dashboard appends client keypairs here."""
    return json.dumps([], indent=2) + "\n"


def server_public_for_env(p: Params) -> str:
    """The WG server public key to surface in .env (WG_SERVER_PUB)."""
    return p.wg_public


# Re-exported so callers can compute the tunnel constants without magic numbers.
SERVER_TUNNEL_IP = _SERVER_TUNNEL_IP
TUNNEL_CIDR = _TUNNEL_CIDR
CLIENT_DNS = _DNS
