"""Compose overlay generator.

The repo's ``docker-compose.vpn.yml`` fronts the dashboard with nginx on 8443
(TLS). Mode A has no nginx and no cert, so it needs a small compose overlay to
publish the dashboard directly on the host IP.

Security note: Mode A has no TLS. The dashboard is reachable over plain HTTP on
port 8080 and must be gated by the host/cloud firewall. The VPN protocols
themselves (Reality/HY2/WG/SS) remain the primary public surface.

Applied as a second ``-f`` file on top of the base compose:

    docker compose -f docker-compose.vpn.yml -f docker-compose.modeA.yml \
        up -d --build vpn-api-v3 vpn-dashboard-v3

Reach the dashboard in a browser at:

    http://<server-ip>:8080/v3

B and C reach the dashboard through nginx with a real cert, so they don't use
this overlay.
"""

from __future__ import annotations

from .common import Params

# Port the Mode-A dashboard is published on. Bound to 0.0.0.0 so it's reachable
# in a browser by IP (Mode A has no domain/tunnel). The dashboard container
# listens on :3000 internally. Access is restricted by the host/cloud firewall.
MODE_A_DASHBOARD_PORT = 8080


def build_mode_a_override(p: Params) -> str:
    """``docker-compose.modeA.yml`` — publish the dashboard on the host IP.

    Mode A has no domain, so customers reach the dashboard directly at
    ``http://<server-ip>:8080/v3`` (no SSH tunnel). There is no TLS in Mode A,
    so the firewall must gate who can reach it.
    """
    port = MODE_A_DASHBOARD_PORT
    lines = [
        "# Mode A overlay — generated by install.sh.",
        "# No domain in Mode A, so the dashboard is published on the host IP.",
        f"#   open http://{p.server_ip or '<server-ip>'}:{port}/v3",
        "# No TLS here — the firewall restricts who can reach this port.",
        "services:",
        "  vpn-dashboard-v3:",
        "    ports:",
        f'      - "0.0.0.0:{port}:3000"',
        "",
    ]
    return "\n".join(lines)
