"""``.env`` generator for the install dir.

Produces the single ``.env`` that ``docker compose`` reads (so it must define
every variable referenced by ``docker-compose.vpn.yml``), plus the
``NEXT_PUBLIC_*`` build-time vars that Next.js inlines into the dashboard at
``next build`` time.

Token wiring (the trap the explorer found): the Python API checks
``API_AUTH_TOKEN``; the dashboard sends ``VPN_API_V3_TOKEN``; the compose file
bridges them. We define ``VPN_API_V3_TOKEN`` in the root ``.env`` and let
compose forward it. We do NOT keep a separate ``API_AUTH_TOKEN`` here to avoid
divergence.

For the dashboard build, we also emit ``vpn-dashboard-v3/.env.production``
(Next.js picks it up automatically) with the same ``NEXT_PUBLIC_*`` values so
the baked image points at the operator's own server.
"""

from __future__ import annotations

from .common import Params


def build_root_env(p: Params) -> str:
    """The .env file docker compose reads (lives at install-dir root)."""
    lines: list[str] = []
    lines.append("# Archie install .env — generated by install.sh")
    lines.append("# Do not edit by hand; re-run the installer to regenerate.")
    lines.append(f"# Mode: {p.mode}   Generated for server {p.server_ip}")
    lines.append("")

    # ── identity (public, baked into the dashboard at build time) ──
    lines.append("# ── server identity ──")
    lines.append(f"NEXT_PUBLIC_SERVER_IP={p.server_ip}")
    lines.append(f"SERVER_IP={p.server_ip}")
    if p.server_domain:
        lines.append(f"NEXT_PUBLIC_SERVER_DOMAIN={p.server_domain}")
        lines.append(f"SERVER_DOMAIN={p.server_domain}")
    lines.append(f"NEXT_PUBLIC_SERVER_PORT=443")
    lines.append(f"SERVER_PORT=443")
    lines.append(f"NEXT_PUBLIC_PUBLIC_BASE_URL={p.public_base_url}")
    # Bare PUBLIC_BASE_URL is what docker-compose.release.yml (Option B) passes to
    # the dashboard as NEXT_PUBLIC_PUBLIC_BASE_URL at runtime. Harmless for the
    # source compose, which doesn't reference it.
    lines.append(f"PUBLIC_BASE_URL={p.public_base_url}")
    lines.append(f"NEXT_PUBLIC_BRAND_NAME={p.brand}")
    lines.append(f"BRAND_NAME={p.brand}")
    lines.append("")

    # ── reality (public half distributed to clients; private half only in xray config) ──
    lines.append("# ── VLESS Reality (public values also baked into dashboard) ──")
    lines.append(f"VLESS_PBK={p.reality_pbk}")
    lines.append(f"VLESS_SID={p.reality_sid}")
    lines.append(f"VLESS_SNI={p.reality_sni}")
    lines.append(f"NEXT_PUBLIC_VLESS_PBK={p.reality_pbk}")
    lines.append(f"NEXT_PUBLIC_VLESS_SID={p.reality_sid}")
    lines.append(f"NEXT_PUBLIC_VLESS_SNI={p.reality_sni}")
    lines.append("")

    # ── secrets ──
    lines.append("# ── secrets ──")
    lines.append(f"AUTH_SECRET={p.auth_secret}")
    # Mode A is HTTP (no domain/TLS) — the session cookie must NOT be Secure or
    # the browser drops it and login never sticks. B/C are HTTPS, so keep Secure.
    lines.append(f"AUTH_COOKIE_SECURE={'false' if p.mode == 'A' else 'true'}")
    lines.append(f"# dashboard sends this; compose forwards it to the API as API_AUTH_TOKEN")
    lines.append(f"VPN_API_V3_TOKEN={p.api_token}")
    lines.append(f"ALLOWED_ORIGINS={p.public_base_url}")
    lines.append("")

    # ── hysteria / wireguard ──
    lines.append("# ── protocol material ──")
    lines.append(f"HYSTERIA_PASSWORD={p.hysteria_password}")
    lines.append(f"WG_SERVER_PUB={p.wg_public}")
    lines.append("")

    # ── internal paths (container-internal, stable) ──
    lines.append("# ── paths (container-internal defaults; compose mounts host paths) ──")
    lines.append("XRAY_CFG=/etc/xray/config.json")
    lines.append("STATE_DIR=/app/vpn-api")
    lines.append("DATA_DIR=/app/data")
    lines.append("USER_META_FILE=/app/data/user_meta.json")
    lines.append("WG_CLIENTS_FILE=/etc/wireguard/clients.json")
    lines.append("VPN_API_INTERNAL_URL=http://vpn-api-v3:5900")
    lines.append("")

    # ── logging paths (host bind-mounts) ──
    lines.append("# ── host log paths (mounted read-only into containers) ──")
    lines.append("LOG_ACCESS=/var/log/xray/access.log")
    lines.append("LOG_AUTH=/var/log/host/auth.log")
    lines.append("LOG_F2B=/var/log/host/fail2ban.log")
    lines.append("")

    # ── dashboard build/runtime ──
    lines.append("# ── dashboard ──")
    lines.append("NEXT_PUBLIC_BASE_PATH=/v3")
    lines.append("NEXT_PUBLIC_SECURITY_PAGE_PATH=/security-review")
    lines.append("")

    # ── optional integrations ──
    if p.abuseipdb_key:
        lines.append("# ── AbuseIPDB ──")
        lines.append(f"ABUSEIPDB_API_KEY={p.abuseipdb_key}")
        lines.append("")
    if p.tg_token:
        lines.append("# ── Telegram alerts ──")
        lines.append(f"TELEGRAM_BOT_TOKEN={p.tg_token}")
        lines.append(f"TELEGRAM_CHAT_ID={p.tg_chat_id}")
        lines.append(f"TELEGRAM_WEBHOOK_URL={p.public_base_url}/vpn-api/telegram")
        lines.append("")

    # ── SMTP invite email (runtime; compose forwards these to the dashboard) ──
    # Emitted only when a host is supplied and SMTP wasn't disabled. The app
    # treats host+from as the "configured" bar; operators can still override any
    # field later in Settings (stored override wins per-field over these).
    if p.smtp_host and not p.no_smtp:
        lines.append("# ── SMTP invite email (optional) ──")
        lines.append(f"SMTP_HOST={p.smtp_host}")
        if p.smtp_port:
            lines.append(f"SMTP_PORT={p.smtp_port}")
        if p.smtp_secure:
            lines.append(f"SMTP_SECURE={p.smtp_secure}")
        if p.smtp_user:
            lines.append(f"SMTP_USER={p.smtp_user}")
        if p.smtp_pass:
            lines.append(f"SMTP_PASS={p.smtp_pass}")
        if p.smtp_from:
            lines.append(f"SMTP_FROM={p.smtp_from}")
        lines.append("")

    return "\n".join(lines) + "\n"


def build_dashboard_env_production(p: Params) -> str:
    """``vpn-dashboard-v3/.env.production`` — Next.js inlines these at build time.

    Only the NEXT_PUBLIC_* values belong here (plus the few non-public vars the
    build step itself needs). Runtime-only secrets stay in the root .env.
    """
    lines: list[str] = []
    lines.append("# Next.js build-time env — baked into the standalone bundle.")
    lines.append("# Regenerate via install.sh; do not edit.")
    lines.append(f"NEXT_PUBLIC_SERVER_IP={p.server_ip}")
    if p.server_domain:
        lines.append(f"NEXT_PUBLIC_SERVER_DOMAIN={p.server_domain}")
    lines.append("NEXT_PUBLIC_SERVER_PORT=443")
    lines.append(f"NEXT_PUBLIC_PUBLIC_BASE_URL={p.public_base_url}")
    lines.append(f"NEXT_PUBLIC_BRAND_NAME={p.brand}")
    lines.append(f"NEXT_PUBLIC_VLESS_PBK={p.reality_pbk}")
    lines.append(f"NEXT_PUBLIC_VLESS_SID={p.reality_sid}")
    lines.append(f"NEXT_PUBLIC_VLESS_SNI={p.reality_sni}")
    lines.append("NEXT_PUBLIC_BASE_PATH=/v3")
    lines.append("NEXT_PUBLIC_SECURITY_PAGE_PATH=/security-review")
    return "\n".join(lines) + "\n"
