"""Hysteria2 ``config.yaml`` generator.

No Hysteria2 template exists anywhere in the repo, so this is authored fresh
against the hysteria-server v2 schema (``listen``, ``tls``, ``auth``,
``masquerade``).

- **Mode A:** self-signed TLS cert (no domain). Clients use ``insecure=1``.
- **Mode B/C:** reuse the deployed cert. We reference the same PEM paths nginx
  uses so the operator supplies one cert pair. The bash layer copies them into
  ``/etc/hysteria/`` during apply (deferred step).

The dashboard's HY2 share format (``sub-formats.ts``) builds URIs as
``hysteria2://<user>:<uuid>@<ip>:2096/?insecure=<0|1>&sni=<domain>`` with
``auth=<user>:<uuid>`` — so the server must accept password auth where each
client's password is ``<user>:<uuid>``. We use ``auth.type: password`` with a
generated bootstrap password and document that per-client passwords are
provisioned by the dashboard.
"""

from __future__ import annotations

from .common import Params


def build_config(p: Params, cert_path: str = "", key_path: str = "", insecure: bool = False) -> str:
    """Return hysteria2 config.yaml text.

    Args:
        p: install params.
        cert_path / key_path: on-host PEM paths the apply step stages. May be
            passed positionally (tests) or by keyword (assembler).
        insecure: True for Mode A (self-signed) so the server doesn't enforce
            SNI hostname checks the self-signed cert can't satisfy.
    """
    lines: list[str] = []
    lines.append("# Hysteria2 server config — generated by install.sh")
    lines.append(f"# Mode: {p.mode}")
    lines.append("listen: :2096")
    lines.append("")
    lines.append("tls:")
    lines.append(f"  cert: {cert_path}")
    lines.append(f"  key: {key_path}")
    if insecure:
        # The server still presents a cert; this only relaxes SNI matching for
        # the self-signed Mode-A case. Clients must use insecure=1 too.
        lines.append("  # self-signed (Mode A) — clients use insecure=1")
    lines.append("")
    # userpass map (matches the reference deployment + the dashboard's HY2
    # provisioning). Seeded with one bootstrap operator; per-client user:uuid
    # pairs are added by the dashboard at runtime.
    lines.append("auth:")
    lines.append("  type: userpass")
    lines.append("  userpass:")
    lines.append(f"    operator: {p.hysteria_password}")
    lines.append("")
    # masquerade.proxy schema (hysteria2 v2): forward unauthenticated probes to a
    # decoy site so the endpoint looks like an ordinary HTTPS reverse proxy.
    lines.append("masquerade:")
    lines.append("  type: proxy")
    lines.append("  proxy:")
    lines.append(f"    url: https://{p.reality_sni}")
    lines.append("    rewriteHost: true")
    lines.append("")
    lines.append("bandwidth:")
    lines.append("  up: 1 gbps")
    lines.append("  down: 1 gbps")
    lines.append("")
    lines.append("quic:")
    lines.append("  initStreamReceiveWindow: 8388608")
    lines.append("  maxStreamReceiveWindow: 8388608")
    lines.append("  initConnReceiveWindow: 20971520")
    lines.append("  maxConnReceiveWindow: 20971520")
    lines.append("  maxIdleTimeout: 30s")
    lines.append("  maxIncomingStreams: 1024")
    lines.append("  disablePathMTUDiscovery: false")
    lines.append("")
    return "\n".join(lines)


def cert_paths() -> tuple[str, str]:
    """On-host cert paths the apply step stages into /etc/hysteria/."""
    return ("/etc/hysteria/cert.pem", "/etc/hysteria/key.pem")
