"""nginx config generator.

We emit a fresh, mode-specific ``conf.d/archie.conf`` plus the matching
``nginx.conf`` main file — generated from the operator's own install values,
never copied from any reference deployment.

- **Mode A:** nginx is optional; if brought up it only reverse-proxies the
  dashboard. No TLS, no stream block, no WS/gRPC routing (Reality + HY2 + WG
  are host-direct and don't need nginx).
- **Mode B (CF Origin cert):** 8443 TLS server using
  ``/etc/ssl/cloudflare-origin.{pem,key}``, CF-IP allowlist include, WS/gRPC
  locations to ``172.20.0.1:1000x``, plus the ``stream{}`` 2053→10003 block.
- **Mode C (Let's Encrypt):** identical to B but the cert path is the LE
  ``live/<domain>/`` pair and we add a port-80 ``acme-challenge`` + redirect
  server so certbot's webroot issuance works.

We also emit the nginx mount artifacts the compose file references but the repo
doesn't ship: ``nginx/html/`` (placeholder index), ``nginx/cloudflare-ips.conf``
(B only), and ``nginx/htpasswd`` (only when ``--dashboard-basic-auth``).
"""

from __future__ import annotations

from .common import Params

# Host-gateway IP of the ailab bridge (172.20.0.0/16). Xray listens on these.
_HOST = "172.20.0.1"


def build_nginx_conf(p: Params) -> str:
    """Main nginx.conf. Mode A has no stream block; B/C include the 2053 SNI proxy."""
    lines: list[str] = []
    lines.append("# nginx.conf — generated by install.sh")
    lines.append("user nginx;")
    lines.append("worker_processes auto;")
    lines.append("error_log /var/log/nginx/error.log warn;")
    lines.append("pid /var/run/nginx.pid;")
    lines.append("")
    lines.append("events { worker_connections 1024; }")
    lines.append("")
    lines.append("http {")
    lines.append("    include       /etc/nginx/mime.types;")
    lines.append("    default_type  application/octet-stream;")
    lines.append("    add_header X-Frame-Options \"SAMEORIGIN\" always;")
    lines.append("    add_header X-Content-Type-Options \"nosniff\" always;")
    lines.append("    add_header X-XSS-Protection \"1; mode=block\" always;")
    lines.append("    add_header Referrer-Policy \"strict-origin-when-cross-origin\" always;")
    lines.append("    server_tokens off;")
    lines.append("    log_format main '$remote_addr - $remote_user [$time_local] \"$request\" '")
    lines.append("                    '$status $body_bytes_sent \"$http_referer\" '")
    lines.append("                    '\"$http_user_agent\"';")
    lines.append("    access_log /var/log/nginx/access.log main;")
    lines.append("    sendfile on;")
    lines.append("    keepalive_timeout 65;")
    lines.append("    proxy_buffer_size 128k;")
    lines.append("    proxy_buffers 4 256k;")
    lines.append("    proxy_busy_buffers_size 256k;")
    lines.append("    client_max_body_size 50M;")
    lines.append("    gzip on;")
    lines.append("    gzip_types text/plain application/json application/javascript text/css;")
    lines.append("    include /etc/nginx/conf.d/*.conf;")
    lines.append("}")
    if p.mode in ("B", "C"):
        cert, key = _tls_cert_key(p)
        lines.append("")
        lines.append("stream {")
        lines.append(f"    ssl_certificate     {cert};")
        lines.append(f"    ssl_certificate_key {key};")
        lines.append("    ssl_protocols       TLSv1.2 TLSv1.3;")
        lines.append("    ssl_ciphers         HIGH:!aNULL:!MD5;")
        lines.append("    server {")
        lines.append("        listen      2053 ssl;")
        lines.append(f"        proxy_pass  {_HOST}:10003;")
        lines.append("        proxy_connect_timeout 10s;")
        lines.append("        proxy_timeout 600s;")
        lines.append("    }")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _tls_cert_key(p: Params) -> tuple[str, str]:
    if p.mode == "B":
        return ("/etc/ssl/cloudflare-origin.pem", "/etc/ssl/cloudflare-origin.key")
    # Mode C: Let's Encrypt live path
    return (
        f"/etc/letsencrypt/live/{p.server_domain}/fullchain.pem",
        f"/etc/letsencrypt/live/{p.server_domain}/privkey.pem",
    )


def build_archie_conf(p: Params) -> str:
    """conf.d/archie.conf — the server block(s) for the dashboard + protocol routing."""
    lines: list[str] = []
    lines.append("# conf.d/archie.conf — generated by install.sh")
    lines.append("")

    if p.mode == "A":
        lines.append("# Mode A: dashboard reverse-proxy only. No TLS, no CDN routing.")
        lines.append("upstream archie_dashboard { server vpn-dashboard-v3:3000; }")
        lines.append("upstream archie_api { server vpn-api-v3:5900; }")
        lines.append("server {")
        lines.append("    listen 80;")
        lines.append(f"    server_name {p.server_ip};")
        lines.append("    location /v3/api/sub/ { proxy_pass http://archie_api; }")
        lines.append("    location /v3/vpn-api/ { proxy_pass http://archie_api; }")
        # A `proxy_pass`-backed location ending in "/" makes nginx itself
        # 301-redirect a bare "/v3" (no trailing slash) request to "/v3/" —
        # but Next.js's basePath canonical form has NO trailing slash, so it
        # immediately redirects "/v3/" back to "/v3". The two redirects fight
        # forever (verified live: infinite loop, ERR_TOO_MANY_REDIRECTS). The
        # exact-match location lets bare "/v3" reach the app directly, without
        # nginx injecting its own competing opinion on the trailing slash.
        lines.append("    location = /v3 { proxy_pass http://archie_dashboard; }")
        lines.append("    location /v3/ { proxy_pass http://archie_dashboard; }")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    # Modes B / C
    cert, key = _tls_cert_key(p)
    domain = p.server_domain
    lines.append(f"upstream archie_dashboard {{ server vpn-dashboard-v3:3000; }}")
    lines.append(f"upstream archie_api {{ server vpn-api-v3:5900; }}")
    lines.append("")

    # Port 80 — LE http-challenge (C) + redirect to TLS (B/C)
    lines.append("# HTTP → HTTPS redirect (+ acme-challenge for Let's Encrypt)")
    lines.append("server {")
    lines.append("    listen 80;")
    lines.append(f"    server_name {domain};")
    if p.mode == "C":
        lines.append("    location /.well-known/acme-challenge/ {")
        lines.append("        root /var/www/certbot;")
        lines.append("    }")
    lines.append("    location / { return 301 https://$host$request_uri; }")
    lines.append("}")
    lines.append("")

    # Port 8443 — TLS dashboard + protocol routing
    lines.append("# HTTPS — dashboard + CDN-fronted protocol routing")
    lines.append("server {")
    lines.append("    listen 8443 ssl;")
    lines.append(f"    server_name {domain};")
    lines.append(f"    ssl_certificate     {cert};")
    lines.append(f"    ssl_certificate_key {key};")
    lines.append("    ssl_protocols       TLSv1.2 TLSv1.3;")
    lines.append("    ssl_ciphers         HIGH:!aNULL:!MD5;")
    if p.mode == "B":
        lines.append("    include /etc/nginx/cloudflare-ips.conf;")
    if p.dashboard_basic_auth:
        lines.append("    auth_basic \"Archie\";")
        lines.append("    auth_basic_user_file /etc/nginx/htpasswd;")
        lines.append("    # Subscription endpoints bypass basic auth (clients can't prompt):")
        lines.append("    location /v3/api/sub/ { auth_basic off; proxy_pass http://archie_api; }")
    else:
        lines.append("    location /v3/api/sub/ { proxy_pass http://archie_api; }")
    lines.append("    location /v3/vpn-api/ { proxy_pass http://archie_api; }")
    # A `proxy_pass`-backed location ending in "/" makes nginx itself
    # 301-redirect a bare "/v3" (no trailing slash) request to "/v3/" — but
    # Next.js's basePath canonical form has NO trailing slash, so it
    # immediately redirects "/v3/" back to "/v3". The two redirects fight
    # forever (verified live: infinite loop, ERR_TOO_MANY_REDIRECTS). The
    # exact-match location lets bare "/v3" reach the app directly, without
    # nginx injecting its own competing opinion on the trailing slash.
    lines.append("    location = /v3 { proxy_pass http://archie_dashboard; }")
    lines.append("    location /v3/ { proxy_pass http://archie_dashboard; }")
    lines.append("")
    # WS / gRPC protocol routing to host Xray
    lines.append("    # CDN-fronted protocols → host Xray via ailab bridge")
    lines.append("    location /vmess-ws { proxy_pass http://%s:10001; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection \"upgrade\"; }" % _HOST)
    lines.append("    location /vmess-grpc { grpc_pass grpc://%s:10002; }" % _HOST)
    lines.append("    location /vless-ws { proxy_pass http://%s:10004; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection \"upgrade\"; }" % _HOST)
    lines.append("    location /vless-grpc { grpc_pass grpc://%s:10005; }" % _HOST)
    lines.append("    location /trojan-ws { proxy_pass http://%s:10006; proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection \"upgrade\"; }" % _HOST)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build_cloudflare_ips_conf() -> str:
    """Cloudflare IPv4/IPv6 allowlist (Mode B). Refresh periodically."""
    lines: list[str] = []
    lines.append("# Cloudflare origin IP allowlist — generated by install.sh")
    lines.append("# Source: https://www.cloudflare.com/ips/")
    lines.append("# (apply step should refresh from the live list; this is a seed)")
    cf_v4 = [
        "173.245.48.0/20", "103.21.244.0/22", "103.22.200.0/22",
        "103.31.4.0/22", "141.101.64.0/18", "108.162.192.0/18",
        "190.93.240.0/20", "188.114.96.0/20", "197.234.240.0/22",
        "198.41.128.0/17", "162.158.0.0/15", "104.16.0.0/13",
        "104.24.0.0/14", "172.64.0.0/13", "131.0.72.0/22",
    ]
    cf_v6 = [
        "2400:cb00::/32", "2606:4700::/32", "2803:f800::/32",
        "2405:b500::/32", "2405:8100::/32", "2a06:98c0::/29",
        "2c0f:f248::/32",
    ]
    for ip in cf_v4:
        lines.append(f"allow {ip};")
    for ip in cf_v6:
        lines.append(f"allow {ip};")
    lines.append("deny all;")
    lines.append("")
    return "\n".join(lines)


def build_html_index(p: Params) -> str:
    """Placeholder index page for nginx/html (so the root isn't 403)."""
    return (
        "<!doctype html><html><head><meta charset=utf-8>"
        f"<title>{p.brand}</title></head>"
        f"<body><h1>{p.brand}</h1>"
        f'<p>Dashboard at <a href="{p.base_path}/">{p.base_path}/</a></p>'
        "</body></html>\n"
    )


def build_htpasswd_placeholder() -> str:
    """Empty htpasswd placeholder. The operator adds users with htpasswd(1)."""
    return "# populate with: htpasswd -c /etc/nginx/htpasswd <user>\n"
